### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by pozsa** [paulscherrerinstitute/alphafold-on-fire#18]
Deployment is one of the first things I'd like to work on, so the site and progress are always ready for a demo.
Any thoughts or preferences on where to deploy to?

(I'm happy to use a personal account of mine from a cloud provider to deploy.)

**Comment by pozsa** [comment]
@sbliven @minottic any preferences for deployment?

**Comment by minottic** [comment]
not really, the hetzner cluster is ready to be used if Stephan agrees...

**Comment by pozsa** [comment]
We can use and deploy to hetzner (we might need to migrate to switch later this year)
